-- Find total customers by countries
SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender
SELECT 
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category
SELECT 
	category,
	COUNT(product_key) AS total_products,
	COUNT(DISTINCT product_id) AS total_products2
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- What is the average costs in each category?
SELECT 
	category,
	AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC

-- What is the total revenue generated for each category?
	-- will get total_revenue only through 'fact_sales' table and 'sales_amount'
SELECT
	p.category,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p 
	ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Find total revenue is generated by each customer
	-- High Cardinality Dimension : Dimension with large number of unique values
	--	(e.g. Product, Customer, Address, ... )
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c 
	ON c.customer_key = f.customer_key
GROUP BY c.customer_key, 
		c.first_name, 
		c.last_name
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?
	-- 'Low Cardinality Dimension' : Dimesnion with few unique values 
	--	(Eg, Category, Country, Gender,...) 
SELECT
	c.country,
	SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
	ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC


-- All 3 Gold Layer Table 
SELECT * FROM gold.dim_customers
SELECT * FROM gold.fact_sales 
-- SELECT * FROM gold.dim_products